version: "0.2"
ignorePaths:
  - .env
  - .gitignore
dictionaryDefinitions: []
dictionaries: []
words:
  - catno
  - daisyui
  - discogs
  - in_wantlist
  - namevariations
  - turbopack
ignoreWords: []
import: []
